# Program name
NAME = libft.a

# Directories
INC_DIR = inc/
SRC_DIR = src/
OBJ_DIR = obj/

# Source files
FTIS_DIR =		$(SRC_DIR)ft_is/ft_isalnum.c \
				$(SRC_DIR)ft_is/ft_isalpha.c \
				$(SRC_DIR)ft_is/ft_isascii.c \
				$(SRC_DIR)ft_is/ft_isdigit.c \
				$(SRC_DIR)ft_is/ft_isprint.c 
FTMEM_DIR =		$(SRC_DIR)ft_mem/ft_bzero.c \
				$(SRC_DIR)ft_mem/ft_calloc.c \
				$(SRC_DIR)ft_mem/ft_memchr.c \
				$(SRC_DIR)ft_mem/ft_memcmp.c \
				$(SRC_DIR)ft_mem/ft_memcpy.c \
				$(SRC_DIR)ft_mem/ft_memmove.c \
				$(SRC_DIR)ft_mem/ft_memset.c
FTPUT_DIR =		$(SRC_DIR)ft_put/ft_putchar_fd.c \
				$(SRC_DIR)ft_put/ft_putendl_fd.c \
				$(SRC_DIR)ft_put/ft_putnbr_fd.c \
				$(SRC_DIR)ft_put/ft_putstr_fd.c
FTTO_DIR =		$(SRC_DIR)ft_to/ft_atoi.c \
				$(SRC_DIR)ft_to/ft_itoa.c \
				$(SRC_DIR)ft_to/ft_tolower.c \
				$(SRC_DIR)ft_to/ft_toupper.c
FTSTR_DIR =		$(SRC_DIR)ft_str/ft_split_mult_c.c \
				$(SRC_DIR)ft_str/ft_split.c \
				$(SRC_DIR)ft_str/ft_strchr.c \
				$(SRC_DIR)ft_str/ft_strcmp.c \
				$(SRC_DIR)ft_str/ft_strdup.c \
				$(SRC_DIR)ft_str/ft_striteri.c \
				$(SRC_DIR)ft_str/ft_strjoin.c \
				$(SRC_DIR)ft_str/ft_strlcat.c \
				$(SRC_DIR)ft_str/ft_strlcpy.c \
				$(SRC_DIR)ft_str/ft_strlen.c \
				$(SRC_DIR)ft_str/ft_strmapi.c \
				$(SRC_DIR)ft_str/ft_strncmp.c \
				$(SRC_DIR)ft_str/ft_strncpy.c \
				$(SRC_DIR)ft_str/ft_strnstr.c \
				$(SRC_DIR)ft_str/ft_strrchr.c \
				$(SRC_DIR)ft_str/ft_strtrim.c \
				$(SRC_DIR)ft_str/ft_substr.c
FTLST_DIR =		$(SRC_DIR)ft_lst/ft_lstadd_back.c \
				$(SRC_DIR)ft_lst/ft_lstadd_front.c \
				$(SRC_DIR)ft_lst/ft_lstclear.c \
				$(SRC_DIR)ft_lst/ft_lstdelone.c \
				$(SRC_DIR)ft_lst/ft_lstiter.c \
				$(SRC_DIR)ft_lst/ft_lstlast.c \
				$(SRC_DIR)ft_lst/ft_lstmap.c \
				$(SRC_DIR)ft_lst/ft_lstnew.c \
				$(SRC_DIR)ft_lst/ft_lstsize.c
GNL_DIR = 		$(SRC_DIR)get_next_line/get_next_line_bonus.c \
				$(SRC_DIR)get_next_line/get_next_line_utils_bonus.c

# Concatenate all source files
SRC =	$(FTIS_DIR) $(FTMEM_DIR) $(FTPUT_DIR) $(FTTO_DIR) \
		$(FTSTR_DIR) $(FTLST_DIR) $(GNL_DIR)

# Generate the list of object files in OBJ_DIR from source files in SRC
OBJ = $(patsubst $(SRC_DIR)%.c,$(OBJ_DIR)%.o,$(SRC))

# Compielr & flags
CC = cc
CFLAGS = -Wall -Wextra -Werror

# Commands
RM = rm -f
AR = ar rcs

# Build rules
all: $(NAME)

$(NAME): $(OBJ)
	@$(AR) $(NAME) $(OBJ)

$(OBJ_DIR)%.o: $(SRC_DIR)%.c
	@mkdir -p $(@D)
	@$(CC) $(CFLAGS) -I$(INC_DIR) -c $< -o $@

clean:
	@$(RM) -r $(OBJ_DIR)

fclean: clean
	@$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
